apiVersion: v1
kind: Service
metadata:
  name: front-react-next
  labels:
    app: front-react-next
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 3000
  selector:
    app: front-react-next
